require('../../1-plugins/chartjs/_chartjs.js')
require('../../2-base-blocks/_modal.js')
require('../../3-blocks/_header.js')
require('../../3-blocks/_downChart.js')
require('../../3-blocks/_faq.js')
require('../../3-blocks/_reportProblem.js')
